# Generated by Django 3.1.7 on 2021-05-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='phonenumber',
            field=models.IntegerField(max_length=10),
        ),
    ]
