# Generated by Django 3.2 on 2021-05-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='licensenumber',
            field=models.CharField(max_length=200),
        ),
    ]
