# Generated by Django 3.1.7 on 2021-05-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalan', '0002_auto_20210509_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='licensenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='challan',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
