# Generated by Django 3.2 on 2021-05-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalan', '0003_alter_challan_vehicletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='dynamicAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='challan',
            name='vehicletype',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
