# Generated by Django 3.1.7 on 2021-05-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chalan', '0004_auto_20210509_1308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='challan',
            new_name='chalan',
        ),
    ]
