# Generated by Django 3.2 on 2021-05-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalan', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='phonenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phonenumbers',
            field=models.IntegerField(),
        ),
    ]
