# Generated by Django 3.2 on 2021-05-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalan', '0006_auto_20210514_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, upload_to='db.sqlite3')),
            ],
        ),
    ]
