# Generated by Django 3.1.7 on 2021-04-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chalan_amount', models.IntegerField()),
                ('chalan_on_name', models.CharField(max_length=100)),
                ('creator_officer', models.CharField(max_length=100)),
            ],
        ),
    ]
